"""Initial migration

Revision ID: 4e37cc12c811
Revises: 
Create Date: 2026-09-13 15:51:34.163839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e37cc12c811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('mt5_server', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_code'), 'brokers', ['code'], unique=True)
    op.create_index(op.f('ix_brokers_name'), 'brokers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mt5_password_encrypted', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'email', name='uq_users_broker_email'),
    sa.UniqueConstraint('broker_id', 'phone', name='uq_users_broker_phone'),
    sa.UniqueConstraint('broker_id', 'username', name='uq_users_broker_username')
    )
    op.create_index(op.f('ix_users_broker_id'), 'users', ['broker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_broker_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brokers_name'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_code'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
